### ISSUE TITLE
SLURM libraries not recognized during SLURM DRMAA install on CentOS EC2 image

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/ansible-cloudman-image#14]
I'm trying to install SLURM DRMAA on a CentOS image and I'm running into problems installing it from source. I'm aware that CentOS doesn't have the nice slurm-drmaa package. I'm not sure why slurm-drmaa is not recognizing the library locations.

Ansible output

```
user@somewhere>ansible-playbook playbook.yml -i hosts -vvvv

PLAY [image-builder] ********************************************************** 

GATHERING FACTS *************************************************************** 
<1.2.3.4> ESTABLISH CONNECTION FOR USER: root
<1.2.3.4> REMOTE_MODULE setup
<1.2.3.4> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="key.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 1.2.3.4 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442328856.98-38639039591782 && echo $HOME/.ansible/tmp/ansible-tmp-1442328856.98-38639039591782'
<1.2.3.4> PUT /tmp/tmpCMnJ7S TO /root/.ansible/tmp/ansible-tmp-1442328856.98-38639039591782/setup
<1.2.3.4> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="key.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 1.2.3.4 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1442328856.98-38639039591782/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1442328856.98-38639039591782/ >/dev/null 2>&1'
ok: [1.2.3.4]

TASK: [ralston.galaxy-os-flexible | Add custom Galaxy PPA (used for nginx package) for Ubuntu] *** 
skipping: [1.2.3.4]

TASK: [ralston.galaxy-os-flexible | Add Docker repository key Ubuntu] ********* 
skipping: [1.2.3.4]

TASK: [ralston.galaxy-os-flexible | Add Docker repository for Ubuntu] ********* 
skipping: [1.2.3.4]

TASK: [ralston.galaxy-os-flexible | Update APT cache] ************************* 
skipping: [1.2.3.4]

TASK: [ralston.galaxy-os-flexible | Install required system packages for Ubuntu] *** 
skipping: [1.2.3.4]

TASK: [ralston.galaxy-os-flexible | Install lxc-docker if installing packages on Ubuntu] *** 
skipping: [1.2.3.4]

TASK: [ralston.galaxy-os-flexible | Install development tools for CentOS] ***** 
skipping: [1.2.3.4]

TASK: [ralston.galaxy-os-flexible | Install required system packages for CentOS] *** 
skipping: [1.2.3.4]

TASK: [ralston.galaxy-os-flexible | Install supervisor for CentOS (yum package is out of date)] *** 
<1.2.3.4> ESTABLISH CONNECTION FOR USER: root
<1.2.3.4> REMOTE_MODULE pip name=supervisor state=present
<1.2.3.4> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="key.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 1.2.3.4 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442328859.87-138621514016632 && echo $HOME/.ansible/tmp/ansible-tmp-1442328859.87-138621514016632'
<1.2.3.4> PUT /tmp/tmpznMmJ_ TO /root/.ansible/tmp/ansible-tmp-1442328859.87-138621514016632/pip
<1.2.3.4> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="key.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 1.2.3.4 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1442328859.87-138621514016632/pip; rm -rf /root/.ansible/tmp/ansible-tmp-1442328859.87-138621514016632/ >/dev/null 2>&1'
ok: [1.2.3.4] => {"changed": false, "cmd": "/usr/bin/pip install supervisor", "name": "supervisor", "requirements": null, "state": "present", "stderr": "You are using pip version 7.1.0, however version 7.1.2 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n", "stdout": "Requirement already satisfied (use --upgrade to upgrade): supervisor in /usr/lib/python2.6/site-packages\nRequirement already satisfied (use --upgrade to upgrade): meld3>=0.6.5 in /usr/lib/python2.6/site-packages (from supervisor)\n", "version": null, "virtualenv": null}

TASK: [ralston.galaxy-os-flexible | Install BLCR (for SLURM) for CentOS] ****** 
skipping: [1.2.3.4]

TASK: [ralston.galaxy-os-flexible | Install slurm dependencies for CentOS] **** 
<1.2.3.4> ESTABLISH CONNECTION FOR USER: root
<1.2.3.4> REMOTE_MODULE yum pkg=authd,hdf5,openmpi-devel,pam-devel,hwloc-devel,rrdtool-devel,ncurses-devel,munge-devel state=latest
<1.2.3.4> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="key.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 1.2.3.4 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442328861.36-132410795583244 && echo $HOME/.ansible/tmp/ansible-tmp-1442328861.36-132410795583244'
<1.2.3.4> PUT /tmp/tmpVdQ7AD TO /root/.ansible/tmp/ansible-tmp-1442328861.36-132410795583244/yum
<1.2.3.4> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="key.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 1.2.3.4 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python -tt /root/.ansible/tmp/ansible-tmp-1442328861.36-132410795583244/yum; rm -rf /root/.ansible/tmp/ansible-tmp-1442328861.36-132410795583244/ >/dev/null 2>&1'
ok: [1.2.3.4] => (item=authd,hdf5,openmpi-devel,pam-devel,hwloc-devel,rrdtool-devel,ncurses-devel,munge-devel) => {"changed": false, "item": "authd,hdf5,openmpi-devel,pam-devel,hwloc-devel,rrdtool-devel,ncurses-devel,munge-devel", "msg": "", "rc": 0, "results": ["All packages providing authd are up to date", "All packages providing hdf5 are up to date", "All packages providing openmpi-devel are up to date", "All packages providing pam-devel are up to date", "All packages providing hwloc-devel are up to date", "All packages providing rrdtool-devel are up to date", "All packages providing ncurses-devel are up to date", "All packages providing munge-devel are up to date", ""]}

TASK: [ralston.galaxy-os-flexible | Install SLURM for CentOS] ***************** 
<1.2.3.4> ESTABLISH CONNECTION FOR USER: root
<1.2.3.4> REMOTE_MODULE command wget -O - https://github.com/SchedMD/slurm/archive/slurm-15-08-0-1.tar.gz | tar -xz -C /root && cd /root/slurm-slurm-15-08-0-1 && ./configure && make && make install #USE_SHELL
<1.2.3.4> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="key.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 1.2.3.4 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442328942.73-8825926459714 && echo $HOME/.ansible/tmp/ansible-tmp-1442328942.73-8825926459714'
<1.2.3.4> PUT /tmp/tmp5oHL_K TO /root/.ansible/tmp/ansible-tmp-1442328942.73-8825926459714/command
<1.2.3.4> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="key.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 1.2.3.4 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1442328942.73-8825926459714/command; rm -rf /root/.ansible/tmp/ansible-tmp-1442328942.73-8825926459714/ >/dev/null 2>&1
changed: [1.2.3.4] => {"changed": true, "cmd": "wget -O - https://github.com/SchedMD/slurm/archive/slurm-15-08-0-1.tar.gz | tar -xz -C /root && cd /root/slurm-slurm-15-08-0-1 && ./configure && make && make install", "delta": "0:02:26.188765", "end": "2015-09-15 10:58:09.443313", "rc": 0, "start": "2015-09-15 10:55:43.254548", "stderr": "--2015-09-15 10:55:43--  https://github.com/SchedMD/slurm/archive/slurm-15-08-0-1.tar.gz\n....\n.....<output truncated>\n....\n....\nMaking install in man8\nmake[3]: Entering directory `/root/slurm-slurm-15-08-0-1/doc/man/man8'\nmake[4]: Entering directory `/root/slurm-slurm-15-08-0-1/doc/man/man8'\nmake[4]: Nothing to be done for `install-exec-am'.\n /bin/mkdir -p '/usr/local/share/doc/slurm-15.08.0/html'\n /usr/bin/install -c -m 644 slurmctld.html slurmd.html slurmdbd.html slurmstepd.html spank.html '/usr/local/share/doc/slurm-15.08.0/html'\n /bin/mkdir -p '/usr/local/share/man/man8'\n /usr/bin/install -c -m 644 slurmctld.8 slurmd.8 slurmdbd.8 slurmstepd.8 spank.8 '/usr/local/share/man/man8'\nmake[4]: Leaving directory `/root/slurm-slurm-15-08-0-1/doc/man/man8'\nmake[3]: Leaving directory `/root/slurm-slurm-15-08-0-1/doc/man/man8'\nmake[3]: Entering directory `/root/slurm-slurm-15-08-0-1/doc/man'\nmake[4]: Entering directory `/root/slurm-slurm-15-08-0-1/doc/man'\nmake[4]: Nothing to be done for `install-exec-am'.\nmake[4]: Nothing to be done for `install-data-am'.\nmake[4]: Leaving directory `/root/slurm-slurm-15-08-0-1/doc/man'\nmake[3]: Leaving directory `/root/slurm-slurm-15-08-0-1/doc/man'\nmake[2]: Leaving directory `/root/slurm-slurm-15-08-0-1/doc/man'\nMaking install in html\nmake[2]: Entering directory `/root/slurm-slurm-15-08-0-1/doc/html'\nmake[3]: Entering directory `/root/slurm-slurm-15-08-0-1/doc/html'\nmake[3]: Nothing to be done for `install-exec-am'.\n /bin/mkdir -p '/usr/local/share/doc/slurm-15.08.0/html'\n /usr/bin/install -c -m 644 accounting.html accounting_storageplugins.html acct_gather_energy_plugins.html acct_gather_profile_plugins.html add.html api.html authplugins.html bb_plugins.html big_sys.html bluegene.html burst_buffer.html cgroups.html checkpoint_blcr.html checkpoint_plugins.html cons_res.html cons_res_share.html contributor.html core_spec.html core_spec_plugins.html cpu_management.html cray.html cray_alps.html crypto_plugins.html disclaimer.html dist_plane.html documentation.html download.html elastic_computing.html ext_sensorsplugins.html faq.html gang_scheduling.html gres.html gres_design.html gres_plugins.html hdf5_profile_user_guide.html high_throughput.html ibm.html ibm-pe.html jobacct_gatherplugins.html job_array.html '/usr/local/share/doc/slurm-15.08.0/html'\n /usr/bin/install -c -m 644 job_container_plugins.html job_exit_code.html job_launch.html job_submit_plugins.html jobcompplugins.html launch_plugins.html licenses.html fair_tree.html mail.html man_index.html maui.html mc_support.html meetings.html moab.html mpi_guide.html mpiplugins.html multi_cluster.html news.html overview.html platforms.html plugins.html power_mgmt.html power_save.html power_plugins.html preempt.html preemption_plugins.html priority_multifactor.html priority_multifactor3.html priority_plugins.html proctrack_plugins.html programmer_guide.html prolog_epilog.html publications.html qos.html quickstart_admin.html quickstart.html reservations.html resource_limits.html rosetta.html route_plugin.html '/usr/local/share/doc/slurm-15.08.0/html'\n /usr/bin/install -c -m 644 rpc.html sched_config.html schedplugins.html select_design.html selectplugins.html slurm.html slurmctld_plugstack.html slurm_ug_agenda.html slurm_ug_cfp.html sun_const.html switchplugins.html taskplugins.html team.html testimonials.html topology.html topology_plugin.html troubleshoot.html tutorials.html wckey.html allocation_pies.gif arch.gif bull.jpg coding_style.pdf configurator.html configurator.easy.html entities.gif example_usage.gif hdf5_task_attr.png hdf5_job_outline.png ibm_pe_fig1.png ibm_pe_fig2.png k_function.gif linuxstyles.css lll.gif mc_support.gif plane_ex1.gif plane_ex2.gif plane_ex3.gif plane_ex4.gif plane_ex5.gif '/usr/local/share/doc/slurm-15.08.0/html'\n /usr/bin/install -c -m 644 plane_ex6.gif plane_ex7.gif slurm_logo.png schedmd.png slurm_design.pdf slurmstyles.css Slurm_Entity.pdf Slurm_Individual.pdf sponsors.gif topo_ex1.gif topo_ex2.gif tutorial_intro_files.tar usage_pies.gif '/usr/local/share/doc/slurm-15.08.0/html'\nmake[3]: Leaving directory `/root/slurm-slurm-15-08-0-1/doc/html'\nmake[2]: Leaving directory `/root/slurm-slurm-15-08-0-1/doc/html'\nmake[2]: Entering directory `/root/slurm-slurm-15-08-0-1/doc'\nmake[3]: Entering directory `/root/slurm-slurm-15-08-0-1/doc'\nmake[3]: Nothing to be done for `install-exec-am'.\nmake[3]: Nothing to be done for `install-data-am'.\nmake[3]: Leaving directory `/root/slurm-slurm-15-08-0-1/doc'\nmake[2]: Leaving directory `/root/slurm-slurm-15-08-0-1/doc'\nmake[1]: Leaving directory `/root/slurm-slurm-15-08-0-1/doc'\nmake[1]: Entering directory `/root/slurm-slurm-15-08-0-1'\nmake[2]: Entering directory `/root/slurm-slurm-15-08-0-1'\nmake[2]: Nothing to be done for `install-exec-am'.\n /bin/mkdir -p '/usr/local/include/slurm'\n /usr/bin/install -c -m 644 slurm/pmi.h slurm/slurm.h slurm/slurmdb.h slurm/slurm_errno.h slurm/smd_ns.h slurm/spank.h '/usr/local/include/slurm'\nmake[2]: Leaving directory `/root/slurm-slurm-15-08-0-1'\nmake[1]: Leaving directory `/root/slurm-slurm-15-08-0-1'", "warnings": ["Consider using get_url module rather than running wget"]}

TASK: [ralston.galaxy-os-flexible | Install SLURM DRMAA for CentOS] *********** 
<1.2.3.4> ESTABLISH CONNECTION FOR USER: root
<1.2.3.4> REMOTE_MODULE command cd /home/ec2-user && wget -O - http://apps.man.poznan.pl/trac/slurm-drmaa/downloads/9 | tar -xz -C /home/ec2-user && cd slurm-drmaa-1.0.7 && ./configure --with-slurm-inc=/usr/local/include/slurm --with-slurm-lib=/usr/local/lib/slurm && make && make install #USE_SHELL
<1.2.3.4> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="key.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 1.2.3.4 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1442329089.64-89941162005294 && echo $HOME/.ansible/tmp/ansible-tmp-1442329089.64-89941162005294'
<1.2.3.4> PUT /tmp/tmpfmTYCD TO /root/.ansible/tmp/ansible-tmp-1442329089.64-89941162005294/command
<1.2.3.4> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o IdentityFile="key.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 1.2.3.4 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1442329089.64-89941162005294/command; rm -rf /root/.ansible/tmp/ansible-tmp-1442329089.64-89941162005294/ >/dev/null 2>&1'
failed: [1.2.3.4] => {"changed": true, "cmd": "cd /home/ec2-user && wget -O - http://apps.man.poznan.pl/trac/slurm-drmaa/downloads/9 | tar -xz -C /home/ec2-user && cd slurm-drmaa-1.0.7 && ./configure --with-slurm-inc=/usr/local/include/slurm --with-slurm-lib=/usr/local/lib/slurm && make && make install", "delta": "0:00:09.128111", "end": "2015-09-15 10:58:24.305389", "rc": 1, "start": "2015-09-15 10:58:15.177278", "warnings": []}
stderr: --2015-09-15 10:58:15--  http://apps.man.poznan.pl/trac/slurm-drmaa/downloads/9
Length: 735270 (718K) [application/x-tar]
Saving to: `STDOUT'

     0K .......... .......... .......... .......... ..........  6%  120K 6s
    50K .......... .......... .......... .......... .......... 13%  287K 4s
   100K .......... .......... .......... .......... .......... 20%  480K 3s
   150K .......... .......... .......... .......... .......... 27% 1.29M 2s
   200K .......... .......... .......... .......... .......... 34%  485K 2s
   250K .......... .......... .......... .......... .......... 41%  485K 1s
   300K .......... .......... .......... .......... .......... 48%  711K 1s
   350K .......... .......... .......... .......... .......... 55%  484K 1s
   400K .......... .......... .......... .......... .......... 62% 1.43M 1s
   450K .......... .......... .......... .......... .......... 69%  475K 1s
   500K .......... .......... .......... .......... .......... 76%  484K 0s
   550K .......... .......... .......... .......... .......... 83%  692K 0s
   600K .......... .......... .......... .......... .......... 90%  483K 0s
   650K .......... .......... .......... .......... .......... 97% 1.42M 0s
   700K .......... ........                                   100%  258K=1.6s

2015-09-15 10:58:17 (439 KB/s) - written to stdout [735270/735270]

configure: error:
SLURM libraries/headers not found;
add --with-slurm-inc and --with-slurm-lib with appropriate locations.
stdout: checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for ranlib... ranlib
checking for a BSD-compatible install... /usr/bin/install -c
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... (cached) ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make sets $(MAKE)... (cached) yes
checking whether ln -s works... yes
checking for rst2html... no
checking for rst2html.py... rst2html.py
checking for rst2latex... no
checking for rst2latex.py... rst2latex.py
checking whether gcc accepts -Wno-missing-field-initializers... yes
checking whether gcc accepts -Wno-format-zero-length... yes
checking host system type... (cached) x86_64-unknown-linux-gnu
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
configure: checking for SLURM
checking for SLURM compile flags... -I/usr/local/include/slurm
checking for SLURM library dir... /usr/local/lib/slurm
checking for usable SLURM libraries/headers... *** The SLURM test program failed to link or run. See the file config.log
*** for the exact error that occured.
no

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/playbook.retry

1.2.3.4               : ok=4    changed=1    unreachable=0    failed=1 
```

roles/ralstonm.galaxy-os-flexible/tasks/packages.yml (an altered version of galaxy-os with support for RHEL

```

---
# Install system packages
- name: Add custom Galaxy PPA (used for nginx package) for Ubuntu
  apt_repository: repo="ppa:galaxyproject/nginx" update_cache=no
  when: ansible_distribution == "Ubuntu"

- name: Add Docker repository key Ubuntu
  apt_key: url="https://get.docker.io/gpg" id="A88D21E9"
  when: configure_docker and ansible_distribution == "Ubuntu"

- name: Add Docker repository for Ubuntu
  apt_repository: repo='deb http://get.docker.io/ubuntu docker main' update_cache=no
  when: configure_docker and ansible_distribution == "Ubuntu"

- name: Update APT cache
  apt: update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: Install required system packages for Ubuntu
  apt: pkg={{ item }} state={{ apt_package_state }}
  with_items:
    - ant
    - atop
    - axel
    - bioperl
    - cmake
    - curl
    - g++
    - gcc
    - gfortran
    - git-core
    - htop
    - iftop
    - iotop
    - ipython
    - libffi-dev
    - liblapack-dev
    - libncurses5-dev
    - libopenblas-dev
    - libpam0g-dev
    - libpq-dev
    - libsparsehash-dev
    - make
    - mercurial
    - nginx-extras
    - nmon
    - openssh-server
    - patch
    - postgresql
    - postgresql
    - postgresql-client
    - postgresql-plpython-9.3
    - python-boto
    - python-dev
    - python-prettytable
    - python-psycopg2
    - python-virtualenv
    - python-pip
    - postgresql-server-dev-9.3
    - rsync
    - slurm-drmaa-dev
    - supervisor
    - swig
    - sysstat
    - unzip
    - vim
    - wget
    - zlib1g-dev
  when: ansible_distribution == "Ubuntu"

- name: Install lxc-docker if installing packages on Ubuntu
  apt: pkg={{ item }} state={{ apt_package_state }}
  with_items:
    - "{{ docker_package }}"
  when: configure_docker and install_packages and ansible_distribution == "Ubuntu"

- name: Install development tools for CentOS
  shell: yum groupinstall -y 'Development tools'
  when: ansible_distribution == "CHANGEME"

- name: Install required system packages for CentOS
  yum: pkg={{ item }} state={{ yum_package_state }}
  with_items:
    - ant
    - atop
    - cmake
    - curl
    - gcc-c++
    - gcc
    - gcc-gfortran
    - git
    - htop
    - iftop
    - iotop
    - libffi
    - lapack
    - lapack-devel
    - openblas
    - openblas-devel
    - make
    - mercurial
    - ncurses
    - ncurses-devel
    - ncurses-libs    
    - nginx
    - nmon
    - openssh-server
    - pam-devel
    - patch 
    - perl-devel
    - perl-CPAN
    - postgresql
    - postgresql-devel
    - postgresql-server
    - postgresql-plpython
    - python-boto
    - python-devel
    - python-ipython    
    - python-prettytable
    - python-psycopg2
    - python-virtualenv
    - python-pip
    - rsync
    - sparsehash-devel
    - swig
    - sysstat
    - unzip
    - wget
  when: ansible_distribution == "CHANGEME"

- name: Install supervisor for CentOS (yum package is out of date)
  pip: name=supervisor state=present
  when: ansible_distribution == "CentOS"

- name: Install BLCR (for SLURM) for CentOS
  shell: cd /home/ec2-user && wget http://crd.lbl.gov/assets/Uploads/FTG/Projects/CheckpointRestart/downloads/blcr-0.8.5.tar.gz && rpmbuild -tb --define 'with_multilib 0' blcr-0.8.5.tar.gz && cd /root/rpmbuild/RPMS/x86_64 && yum install blcr* --nogpgcheck -y
  when: ansible_distribution == "CHANGEME"

- name: Install slurm dependencies for CentOS
  yum: pkg={{ item }} state=latest
  with_items:
    - authd
    - hdf5
    - openmpi-devel
    - pam-devel
    - hwloc-devel
    - rrdtool-devel
    - ncurses-devel
    - munge-devel
  when: ansible_distribution == "CentOS"

- name: Install SLURM for CentOS
  shell: wget -O - https://github.com/SchedMD/slurm/archive/slurm-15-08-0-1.tar.gz | tar -xz -C /root && cd /root/slurm-slurm-15-08-0-1 && ./configure && make && make install
  when: ansible_distribution == "CentOS"

- name: Install SLURM DRMAA for CentOS
  shell: cd /home/ec2-user && wget -O - http://apps.man.poznan.pl/trac/slurm-drmaa/downloads/9 | tar -xz -C /root && cd /root/slurm-drmaa-1.0.7 && ./configure --with-slurm-inc=/usr/local/include/slurm --with-slurm-lib=/usr/local/lib/slurm && make && make install
  when: ansible_distribution == "CentOS"

- name: Install get cpanm.pl for CentOS
  get_url: {url: 'https://cpanmin.us/', dest=/tmp/cpanm.pl, mode=755}
  when: ansible_distribution == "CentOS"

- name: Install CPANM for CentOS
  command: perl cpanm.pl App::cpanminus
  args:
    {chdir: /tmp/, creates: /usr/local/bin/cpanm}
  when: ansible_distribution == "CentOS"

- name: Symlink cpanm to /usr/bin for CentOS
  file: {src: /usr/local/bin/cpanm, dest: /usr/bin/cpanm, state: link}
  when: ansible_distribution == "CentOS"

- name: install implicit Bio::Perl dependencies for CentOS
  cpanm: name={{ item }}
  with_items:
    - Time::HiRes
    - LWP::UserAgent
  when: ansible_distribution == "CentOS"

- name: install BioPerl for CentOS
  cpanm: name=Bio::Perl
  when: ansible_distribution == "CentOS"
```
